### ISSUE TITLE
Not having the required credentials is a blocker

### ISSUE THREAD

**Issue by ilanolkies** [rsksmart/rLogin#110]
After accessing the Data Vault and identifying that there are no credentials for the required fields we can prompt the user to a verification service.

We can have a whitelist with, initially, [VC Issuer](https://github.com/rsksmart/email-vc-issuer) url and its address (to compare against the signer of the disclosed credential).

**Comment by jessgusclark** [comment]
I like it! We should check if the datavault URL is RIF's. Just in case in the dapp uses a custom one. Then, after https://github.com/rsksmart/rif-identity-manager/pull/78 gets merged, we could have them link directly to the RIF Id Manager.
