### ISSUE TITLE
Logos are not aligned to middle

### ISSUE THREAD

**Issue by ilanolkies** [rsksmart/rLogin#149]
<img width="281" alt="Screen Shot 2021-09-08 at 12 09 33" src="https://user-images.githubusercontent.com/36084092/132535868-cd48748f-9a5f-45f3-9028-b012ad45a4e5.png">

Now that we removed the description the logos are not correctly aligned to the middle. Picky one

**Comment by jessgusclark** [comment]
Good catch!

In addition, the description paragraph is not longer being used, so it should be removed.
