### ISSUE TITLE
Liquality wallet not working

### ISSUE THREAD

**Issue by mulonemartin** [rsksmart/rLogin#200]
**Step to reproduce:**

1. Connect liquality on testnet network and select RSK on settings
2. Use to reproduce this site: [https://sample-app-multisig.rifos.org/](https://sample-app-multisig.rifos.org/)

Connecting to provider forever...

(ur
![Captura de pantalla de 2021-12-06 16-17-49](https://user-images.githubusercontent.com/793188/144908669-3c3a3fdf-abbf-48f0-9c35-ba5d54b2d144.png)
l)

**Comment by jessgusclark** [comment]
Hello @mulonemartin , I can't reproduce this. I was able to connect after setting Liquality as the default web3 provider, changing to RSK testnet. The first time I did refresh the page to make sure Liquality was injecting the provider.

https://user-images.githubusercontent.com/766679/145203447-1f35aa1e-5b92-4c23-905b-c4e945657104.mov

I would also mention that we never tested Liquality with this **sample** multisig app. This was only really tested with Metamask, although it _should_ work.
