### ISSUE TITLE
WalletConnect is hidden in mobile phones

### ISSUE THREAD

**Issue by ilanolkies** [rsksmart/rLogin#226]
Ref: https://open-rsk-dev.slack.com/archives/C02JVHMHC49/p1646916400849289

**Comment by tkeidar** [comment]
I was able to temporary workaround this issue by adding this to my css:

.rlogin-providers-mobile {
  display: flex !important;
}

**Comment by ilanolkies** [comment]
There is a variable `hideMobile={true}` set on providers https://github.com/rsksmart/rLogin/blob/6e31694ae4ca39ef67945f7357c5c6637d650508/src/ux/step1/WalletProviders.tsx#L89

Testing: see https://docs.cypress.io/api/commands/viewport#Syntax

**Comment by kazazor** [comment]
@ilanolkies not sure what to do with hit information, where can I pass "false" here? It doesn't make sense that wallet connect will not be shown on mobile by default..

**Comment by ilanolkies** [comment]
We need to do a PR to fix it. It needs to be false by default, we agree on that

**Comment by kazazor** [comment]
Great, then this could arrive in the next release of rLogin I believe as it's such a small change :)

**Comment by kazazor** [comment]
@jessgusclark / @ilanolkies - I tested it and it does not work. Wallet connect does not appear by default on mobile.
In addition, it seems that @tkeidar 's workaround is not working anymore.

That means we cannot upgrade to this new version of rLogin as users won't have walletconnect on mobile view.
Can you please take a look at it? If I'm correct then this issue needs to be reopened.
