### ISSUE TITLE
When cacheprovider is enabled, the choose wallet dialog still shows for a quick moment

### ISSUE THREAD

**Issue by kazazor** [rsksmart/rLogin#227]
In [this line](https://github.com/rsksmart/rLogin/blob/4a6babed19c58be6ec0e4cce437fef2b020d194c/src/RLogin.tsx#L216) we show the modal no matter what even if a cacheprovider exists.
I believe it should move to the reject section of the promise.

Me and @ilanolkies looked at it together.

**Comment by ilanolkies** [comment]
To clarify, we are doing `showModal()` even if the cached provider exists and successes to connect. See `visibility` css

https://user-images.githubusercontent.com/36084092/157872072-00952da8-b0e0-4201-aa59-1757d5cf6e5d.mov

The only case when this shouldn't be shown is when
1. developer opts to use mode without authentication,
2. user is connecting to a provider without _choose network step_, and
3. user has selected "Don't show again" on _Confirm information step_.
