### ISSUE TITLE
Resolve web3modal migraiton issues to rLogin within rLogin

### ISSUE THREAD

**Issue by kazazor** [rsksmart/rLogin#229]
When a user that used web3modal (which is very popular) before using rLogin AND the `cacheProvider` option is set to `true`, calling `connect` will fail:
![Screen Shot 2022-03-11 at 1 27 35](https://user-images.githubusercontent.com/1577655/157773469-3770a60c-867a-4ad5-975c-612d6398635f.png)

This is a serious bug as any user who used web3modal will fail with rLogin.

The way to avoid it is to also check if RLOGIN_SELECTED_PROVIDER is defined on localstorage before calling:
```js
await this.providerController.connectToCachedProvider()
```

This should be checked here: https://github.com/rsksmart/rLogin/blob/4a6babed19c58be6ec0e4cce437fef2b020d194c/src/RLogin.tsx#L211

So a solution could be something like:
```js
new Promise(async (resolve, reject) => { // weird async, to be refactored
      this.setupHandlers(resolve, reject)

      if (this.cachedProvider && getLocal(RLOGIN_SELECTED_PROVIDER)) {
        await this.providerController.connectToCachedProvider()
          .catch(() => {
             this.showModal();
             reject();
           })
      } else {
         this.showModal();
      }
    });
```

This solution also takes care of: https://github.com/rsksmart/rLogin/issues/227

P.S:
I used `getLocal` which could be imported from `web3modal`.
If you do not wish to add this condition here (since `RLOGIN_SELECTED_PROVIDER` is not used in this file but instead it's used in `providers.ts`, then you can add this condition in here: https://github.com/rsksmart/rLogin/blob/4c3f728d9c95154a839942a02a12a89ebd8eae97/src/controllers/providers.ts#L219

Just make sure to show the modal if it fails.. M suggestion to add it to the connect function is to not have to fail and reject to begin with and avoid it all together.

--------------

What we did to avoid it for now is:
```js
    let web3CachedProvider = localStorage.getItem("WEB3_CONNECT_CACHED_PROVIDER");
    const rLoginSelectedProvider = localStorage.getItem("RLOGIN_SELECTED_PROVIDER");

    if (web3CachedProvider && !rLoginSelectedProvider) {
      this.rLogin.clearCachedProvider();
    }
```

**Comment by ilanolkies** [comment]
Good catch! We have another proposal for the implementation. Instead of using `WEB3_CONNECT_CACHED_PROVIDER` for detecting if there is cached provider or not, we can use our own variable and avoid depending on what `web3modal` did on `localStorage`. This way, if you migrated from an old app that was using `web3modal`, you are going to see the modal back once again. This would be `hasCachedProvider = localStorage.getItem("RLOGIN_SELECTED_PROVIDER")`

Testing: we can create a _cypres/integration/4-web3modal-migration_ and get this properly tested 😄

**Comment by kazazor** [comment]
The only thing to keep in mind is to also make sure that the getter for cachedProvider will return an appropriate value. Right now it returns "injected" for metamask for example.

**Comment by ilanolkies** [comment]
I opened a new issue for that since it will need more work. I would first fix web3modal bug an then go through that one that is not user facing
