### ISSUE TITLE
Improve message if no wallet exists

### ISSUE THREAD

**Issue by jessgusclark** [rsksmart/rLogin#26]
The heading, "Connect your wallet", should not be shown

![image](https://user-images.githubusercontent.com/766679/99680609-e96a3200-2a85-11eb-97a9-9b06161772ce.png)

**Comment by ilanolkies** [comment]
@jessgusclark is it closed by #107?

**Comment by jessgusclark** [comment]
@ilanolkies Wow! I had forgotten that I submitted this as an issue! Yes, #107 closes this issue.
