### ISSUE TITLE
WalletInfo dialog - bug/ux - Showing the network id means nothing to the user

### ISSUE THREAD

**Issue by kazazor** [rsksmart/rLogin#267]
At the moment, the dialog looks like this:
![Screen Shot 2022-04-30 at 20 08 08](https://user-images.githubusercontent.com/1577655/166115393-83d9b1f7-a2a1-40f5-98d5-b13ee2c24417.png)

Seeing the network id tells me nothing as an end user.
Instead, I would like to see the network name (same as I see it on my metamask/other wallet).
In addition, showing the network icon (if you have it. Also talking about multichains support here) would make sense.

P.S:
Also at the moment it just says the word "Network" twice for no reason

**Comment by jessgusclark** [comment]
Hello Kazaor,

There are a [handful of networks](https://github.com/rsksmart/rLogin/blob/79e8320b139e9fd04a08d529e8137c3089bf65df/src/adapters.ts#L13-L24) that are listed and when the user is connected to one they see the human readable title of the network:

![Screen Shot 2022-05-03 at 11 42 09 AM](https://user-images.githubusercontent.com/766679/166425958-40098bd3-6f9c-48c5-bf31-0a18b9dbe61c.png)


The network you see above is a testing or local network and will only be shown to developers running the service locally. We can add an alias for 1337 but which other networks are you interested in adding?

**Comment by kazazor** [comment]
Ohh got it, my bad here :)

We're looking at also supporting:

1. Fantom Opera - 250
2. Fantom Opera Testnet - 4002
3. Arbitrum - 42161
4. Arbitrum Testnet (Rinkeby) - 421611
5. Polygon - 137
6. Polygon Testnet (Mumbai) - 80001

Would be great adding those :)
