### ISSUE TITLE
Show the nifty wallet option only if the extension is installed (Discourage the use of a discontinued wallet)

### ISSUE THREAD

**Issue by jbokser** [rsksmart/rLogin#278]
Even if the extension is not installed always _Nifty wallet_ option is visible.
This may encourage the user to install _Nifty wallet_ and this wallet is discontinued.

It would be much better to show the _Nifty wallet_ option only if the extension is installed just like it's being done right now with _Tally Ho! wallet_.

![rlogin-nifty](https://user-images.githubusercontent.com/54363233/170132796-48c65614-714e-44a7-905d-fa44107e13c2.jpg)

**Comment by ilanolkies** [comment]
I agree. We can work on this https://github.com/rsksmart/rLogin/issues/262#issuecomment-1137061465 to close this one
