### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by ilanolkies** [rsksmart/rLogin#28]
- [x] Set up framework for i18n
- [x] Move en-US texts to use framework
- [x] Import new translations
- [x] Let user change it from the UI
- [x] Allow developer to choose optionally the supported languages via `supportedLanguages: ELanguages[]`
- [x] Return `selectedLanguage` on rLogin response
- [x] Create a `languageChanged` event to tell the app when changed
- [x] Hide language selector when only one language
- [x] Add translations

**Comment by jessgusclark** [comment]
Steps 1-3 have been completed with #115

**Comment by ilanolkies** [comment]
4 closed with #122

**Comment by ilanolkies** [comment]
5 closed with #125

**Comment by ilanolkies** [comment]
6 closed with #128

**Comment by ilanolkies** [comment]
7 closed with #131

**Comment by ilanolkies** [comment]
8 closed with #133

**Comment by ilanolkies** [comment]
9 closed with #134
