### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [rsksmart/rLogin#300]
Hi everyone.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by jessgusclark** [comment]
Hey @codehangen , sorry for the delay, most of us have been on holiday the past few weeks & just getting back. This project is still active in that it is being used in several project, however, from a development side of things it is mostly in maintenance mode.

**Comment by ghost** [comment]
Hi jessgusclark.

> Hey @codehangen , sorry for the delay, most of us have been on holiday the past few weeks & just getting back. This project is still active in that it is being used in several project, however, from a development side of things it is mostly in maintenance mode.

thank you for feedback here!
